### ISSUE TITLE
Name all selector/method parameters

### ISSUE THREAD

**Issue by joshgav** [OfficeDev/Office-365-SDK-for-iOS#1]
Let's make sure all the selector parameters are name, e.g.
[myObj initWithUrl:@"https://my.site" executeWithCallback:(^)(id response)]

There are places where we just have colons (":") for parameters after the first, which makes the code hard to read. Also, let's not have spaces between the end of the parameter name and the colon, and the colon and the cast operator ("(").

**Comment by greathansen** [comment]
updated in v0.9.0
