### ISSUE TITLE
test/sdk_tests not running

### ISSUE THREAD

**Issue by Mavneesh** [OfficeDev/Office-365-SDK-for-iOS#100]
I have installed all the pods but still the project is not running
Error:
ld: library not found for -lADALiOS
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by Mavneesh** [comment]
I am able to run this now but i am socked to see that all file operations are commented.
Are you working to fix any issue related to File upload.

**Comment by tranhieutt** [comment]
>Are you working to fix any issue related to File upload.
I have trouble similar related to file upload.
I can't upload any file.

**Comment by Mavneesh** [comment]
Yes i have facing this issue and have not fixed yet even this library is not working all file operations code is commented in "SDK_Test".
Keep trying and if you fined any solution please update on this thread.

**Comment by tranhieutt** [comment]
Have you used Office 365 SDK?
If you can use upload function, please notice for me.
Thank you so much!

**Comment by Omfe** [comment]
Excuse me, what was your solution around the clang error? Please help.
Thank you very much!

**Comment by Mavneesh** [comment]
Yes upload in oneDriveBusiness is working now. i have just add "addCustomHeaderWithName:@"If-Match" andValue:@"*"]" in my method.

 [[(MSODataMediaEntityFetcher *)[[[[client getfiles] getById:fileName] asFile] addCustomHeaderWithName:@"If-Match" andValue:@"*"] putContent:body withCallback:^(NSInteger result, NSError *error) 
{

}
] resume];
