### ISSUE TITLE
Building Office 365 pod throws Static analyzer warnings in the Analyze phase 

### ISSUE THREAD

**Issue by shreeb** [OfficeDev/Office-365-SDK-for-iOS#15]
Building the Office 365 pod in the Xcode Bot Server . We hit the following the static analyzer warnings during analyze phase. Can you see if these are issues you can fix  in the next version ?

------------

Analyzer Warning in TestProject/Pods/Office365/sdk-objectivec/office365-lists-sdk/office365-lists-sdk/office365-lists-sdk/ListClient.m
Dead store: Value stored to 'json' during its initialization is never read

Introduced by shreebmac (044e0dc)
Analyzer Warning in TestProject/Pods/Office365/sdk-objectivec/office365_directory_sdk/Generated/Operations/Implementations/MSDirectoryODataEntityFetcher.m
Core Foundation/Objective-C: Returning 'self' while it is not set to the result of '[(super or self) init...]'

Introduced by shreebmac (044e0dc)
Analyzer Warning in TestProject/Pods/Office365/sdk-objectivec/office365_discovery_sdk/Generated/Operations/Implementations/MSDiscoveryODataEntityFetcher.m
Core Foundation/Objective-C: Returning 'self' while it is not set to the result of '[(super or self) init...]'

Introduced by shreebmac (044e0dc)
Analyzer Warning in TestProject/Pods/Office365/sdk-objectivec/office365_odata_base/office365_odata_impl/Implementations/MSODataURLImpl.m
Core Foundation/Objective-C: Returning 'self' while it is not set to the result of '[(super or self) init...]'

Introduced by shreebmac (044e0dc)
Analyzer Warning in TestProject/Pods/Office365/sdk-objectivec/office365_exchange_sdk/Generated/Operations/Implementations/MSOutlookODataEntityFetcher.m
Core Foundation/Objective-C: Returning 'self' while it is not set to the result of '[(super or self) init...]'

Introduced by shreebmac (044e0dc)
Analyzer Warning in TestProject/Pods/Office365/sdk-objectivec/office365_odata_base/office365_odata_impl/Implementations/MSRequestImpl.m
Core Foundation/Objective-C: Returning 'self' while it is not set to the result of '[(super or self) init...]'

Introduced by shreebmac (044e0dc)
Analyzer Warning in TestProject/Pods/Office365/sdk-objectivec/office365_drive_sdk/Generated/Operations/Implementations/MSSharePointODataEntityFetcher.m
Core Foundation/Objective-C: Returning 'self' while it is not set to the result of '[(super or self) init...]'

Introduced by shreebmac (044e0dc)

**Comment by greathansen** [comment]
Fixed in v0.9.0
