### ISSUE TITLE
List sites created within SharePoint

### ISSUE THREAD

**Issue by dorinsimina** [OfficeDev/Office-365-SDK-for-iOS#36]
Hi,

Is there a way using the Office 365 API for iOS to list the sites created from SharePoint?
I've seen that it offers an iOS API for folders and files from SharePoint Online, but I don't know if it covers also my needs.

Thanks in advance.
Dorin

**Comment by anihojnadel** [comment]
Sorry for the delay. 

The SDK's starting point is a particular site. You need a site to create a client and start getting or creating items. So you won't be able to list anything that's not part of that site (e.g. all sites).

You can review Sharepoint REST operations and check if there's a way to get the information you need and extend the SDK accordingly to consume it.

Regards,
Anahí
