### ISSUE TITLE
JsonParser throws error when rertrieving weekly Recurring Calendar Events as MSOutlookEvent object

### ISSUE THREAD

**Issue by jpanchal** [OfficeDev/Office-365-SDK-for-iOS#37]
Hello,

This is very bizarre bug. I tried to retrieve weekly calendar events from exchange using getEvents method on MSOutlookClient, but it fails to convert json payload to array of MSOutlookEvent object when it contains weekly recurring type of calendar event.

It specifically fails for populating DaysOfWeek property at line 394 in JsonParser.m

-(void)setValueForCollection :(Property*)property : (NSDictionary*)data :(id)returnType{
    id object = [data valueForKeyPath:property.Name];
    if([object isKindOfClass:NSNull.class] || object == nil) return;
    NSArray * newData = object;
    Class type = NSClassFromString([property getCollectionEntity]);
    if(type == nil){        
        NSMutableArray* returnData = [NSMutableArray array];     
        for (NSDictionary* dicc in newData) {
            NSString* value = [dicc valueForKey:property.Name];    //<-------- ERROR
.
.
.

Can someone please fix this?

Thanks,

**Comment by jpanchal** [comment]
Any update on this? This is still an issue :(

**Comment by greathansen** [comment]
@jpanchal This issue is related to the enum type(setting the value using runtime is not working) I will review this.

**Comment by greathansen** [comment]
@jpanchal -> A fix was added for the issue. Could you test it with the last version of the Dev Branch?
