### ISSUE TITLE
View SharePoint Files

### ISSUE THREAD

**Issue by karlbarek** [OfficeDev/Office-365-SDK-for-iOS#38]
I know you are able to retrieve lists of files. Is there a way to download a File that is stored in SharePoint and be viewable on the device?

**Comment by anihojnadel** [comment]
Sorry for the delay, this is the code to download the content of a particular file. You can see it working in the following [test](https://github.com/OfficeDev/Office-365-SDK-for-iOS/blob/09de2cd81c349401429bed3bf3f7b05710795557/sdk-objectivec/office365-e2end-tests/office365-e2end-tests/FilesTestRunner.m#L116).


````
MSSharePointClient *sharePointClient;
[[[sharePointClient getfiles]getById:itemId] asFile ] getContentWithCallback:^(NSData *addedContent, MSODataException *error) {
                //Your code
            }];
````
