### ISSUE TITLE
iOS: MSSharePointFolder children array is always nil 

### ISSUE THREAD

**Issue by ravidixit** [OfficeDev/Office-365-SDK-for-iOS#43]
I tried to fetch the folder contents from one drive using the below code, folder contains many sub-directories and files

     NSURLSessionTask* task =  [[[[client getfiles] getById:oneDriveItem.id] asFolder] read:^(MSSharePointFolder *folder, MSODataException *error) {
            if (error==nil) {
                dispatch_async(dispatch_get_main_queue(),
                               ^{
                                   for(MSSharePointItem *items in folder.children){
                                       NSLog(@"name = %@",items.name);
                                       NSLog(@"type = %@",items.type);
                                   }
                               });
            }
          
           
        }];
         [task resume];
    }];
   
Here the folder.children is always nil but the child count property displays the correct count of the folder item.
Can you please review this behavior it's really strange.

**Comment by dorinsimina** [comment]
As a workaround you could call:

[[[client getfiles] getById:self.folder.id] asFolder] getchildren]

**Comment by ravidixit** [comment]
@dorinsimina : Thanks for your quick reply

I have tried above solution and it works fine, 

My case is I have a UITableView displaying both folders and files type in its list, the above code would work if I tap on an folder type but would return an empty child if an individual file is clicked.

So do i need to first check the type and then call asFile / asFolder ? OR just use some URL schema and display the file content in one drive app.

Please provide inputs

**Comment by dorinsimina** [comment]
Yes, depending of the MSSharePointItem type you could add a preview option if the selection is a File or perform children browsing if the selection is a Folder.

**Comment by greathansen** [comment]
@ravidixit also for this case, the children property is a navigation property. For this you have to expand the property in the rest request. So for have the entire folder with the children you have to use the next code (added the expand method with the name of the property)

[[[[[self.Client getfiles] getById:oneDriveItem.id] asFolder] expand:@"children"]           read:^(MSSharePointFolder *folder, MSODataException *error) {
        for(MSSharePointItem *items in folder.children){
            NSLog(@"name = %@",items.name);
            NSLog(@"type = %@",items.type);
        }
}];

**Comment by ravidixit** [comment]
@greathansen Is this documented somewhere like all the classes and their methods purpose n usage maybe something like the MSDN.
