### ISSUE TITLE
Search on List Items

### ISSUE THREAD

**Issue by karlbarek** [OfficeDev/Office-365-SDK-for-iOS#44]
Is there a way to search on a field, i.e. "Title" on a list using the SDK? I know the Android SDK has a query parameter. I'm not seeing it in the iOS SDK.

I have the getListItems returning all my list items, but I haven't figured out how to refine that result.

**Comment by ravidixit** [comment]
@karlbarek can you put in some code so that we can see how are you fetching the list items?
