### ISSUE TITLE
Discovery sample uses AllServices resource - AllServices currently doesn't provide valid URLs

### ISSUE THREAD

**Issue by MIchaelMainer** [OfficeDev/Office-365-SDK-for-iOS#46]
I suggest you change samples to use the Services resource.
 
https://github.com/OfficeDev/Office-365-SDK-for-iOS/blob/master/Samples/simple-discovery-app/simple-discovery-app/Controllers/ServicesTableViewController.m

In ServicesTableViewController.m, 

[BaseController getClient:^(MSDiscoveryClient * client) {
            [[[client getallServices] read:^(NSArray<MSDiscoveryServiceInfo> *serviceInfos, NSError *error) {

Change to:

[BaseController getClient:^(MSDiscoveryClient * client) {
            [[[client getServices] read:^(NSArray<MSDiscoveryServiceInfo> *serviceInfos, NSError *error) {

Or, at a minimum, add a md file to that directory to state that doesn't work right now.

**Comment by greathansen** [comment]
The api is returning a 401 code for api/services. With the get all services (api/allservices) is working fine.
