### ISSUE TITLE
OneDrive - create a folder inside a specific folder

### ISSUE THREAD

**Issue by dorinsimina** [OfficeDev/Office-365-SDK-for-iOS#48]
Is there a way to create in OneDrive a folder inside another folder?

I've tried to setup for a newly created MSSharePointFolder instance its parentReference (MSSharePointItemReference instance with valid parent id and path params), but the folder is still created in my OneDrive's root.

**Comment by dorinsimina** [comment]
I've used the following specifications to create a folder nested inside another folder:
PUT {base-url}/Files/{parent-id}/children/{folder-name}

Since I did not found how to make the call using the SDK, I've created the REST API call on my own.

**Comment by anihojnadel** [comment]
There's a test that actually creates a folder within inbox folder. Bellow you'll find the reference to that piece of code. 

[[_weakSelf.client.me.folders getById:@"Inbox"].childFolders add:newFolder callback:^(MSOutlookFolder *folder, MSOrcError *e) {
        // your code
    }];

https://github.com/OfficeDev/Office-365-SDK-for-iOS/blob/master/test/sdk_tests/sdk_tests/MailTestRunner.m#L724

Let us know if you have any questions.
