### ISSUE TITLE
Run into an OOM

### ISSUE THREAD

**Issue by Kammy6679** [OfficeDev/Office-365-SDK-for-iOS#49]
Using the Office 365 SDK for Android and Office 365 SDK for iOS, we plan to access the OneDrive Business and stored data in our product.
 
We find that: our app runs into an OOM when using Office 365 SDK to upload/download a large file(about 30M or more). Do you have any suggestion for this issue?
 
Here is our download code:
SharePointClient client = ODB_Manager.getInstance().getFileClient();
ListenableFuture<byte[]> future = client.getfiles().getById(id).asFile().addHeader("if-none-match", eTag).getContent();
 
Here is our upload code:
ListenableFuture<Void> future = client.getfiles().getById(item.getid()).asFile().putContent(result);

**Comment by dorinsimina** [comment]
Did you tried to use setChunkedStreamingMode (this approach might help you to chunk your data into specific size, so that you need not keep your entire file in the memory)?

**Comment by joshgav** [comment]
This was addressed with support for streaming uploads and downloads in 0.8+
