### ISSUE TITLE
List items are always nil

### ISSUE THREAD

**Issue by ravidixit** [OfficeDev/Office-365-SDK-for-iOS#52]
I have added the announcement app and added few items to it, now i want to fetch the items from my announcement list so I have used the below code

token_Obtained_During_first_time_Login: This is the token that i get when i login for the first time using the acquireTokenWithResource method of ADAuthenticationContext class

    - (void)getClientList {
    
    NSString *appToken = [[NSUserDefaults standardUserDefaults] valueForKey:@"token_Obtained_During_first_time_Login"];
    NSString* hostName = @"https://myTenant.sharepoint.com/sites/myApp";
    

    OAuthentication *credentials = [[OAuthentication alloc] initWith:appToken];
    ListClient *client = [[ListClient alloc]
                          initWithUrl:hostName
                          credentials:credentials];

    NSURLSessionTask* task =  [client getListItems:@"MyAnnouncements" callback:^(NSMutableArray *listItems, NSError *error)  {
        if (error==nil) {
            NSLog(@"%@",listItems);
        }
    }];
    
    [task resume];
    
    }

I have even debugged the 365 code and it proivides me the below URL for getListItems: callback method

    https://myTenant.sharepoint.com/sites/myApp/_api/lists/GetByTitle('MyAnnouncements')/Items

I have even tried the same using getTokenWith method which comes with the sample code 

    - (void)getAnnouncementList:(void (^)(ListClient *))callback{
    NSString* hostName = @"https://myTenant.sharepoint.com";
    
    [self getTokenWith:hostName :true completionHandler:^(NSString *token) {
        OAuthentication *credentials = [[OAuthentication alloc] initWith:token];
        
        callback([[ListClient alloc]initWithUrl:hostName credentials:credentials]);
         }];
    }

But still no luck i get the list as nil

Please guide on how this can be resolved.

Every time i call the above code i get the response nil not sure what am passing wrong, my guess is the token.

**Comment by jmktayag** [comment]
Hi, were you able to fix this? I was having the same issue. Even though I passed the accesstoken, the list still returns nil. Thanks.

**Comment by ravidixit** [comment]
@jmktayag : yup i was able to do this check my answer in stackoverflow, hope that helps

http://stackoverflow.com/questions/28456595/office-365-ios-not-able-to-fetch-list-items-from-office-365-sdk

**Comment by anihojnadel** [comment]
We fixed the issue, it will be available in next release.
Notice that the url should be changed to @"/_api/web/lists". In the stackoverflow issue you're adding your site too, so that won't be universal for all the users.

Thanks for contributing!
