### ISSUE TITLE
UserInformation.GetEmail doesn't return the currently logged user's email

### ISSUE THREAD

**Issue by ghost** [OfficeDev/Office-365-SDK-for-iOS#53]
UserId property contains the right value, however, getEmail doesn't return anything. How can we get the current user's email address?

Thanks,
Uma

**Comment by ravidixit** [comment]
@UmaSubramanianPersonal : can you display the some portion of your code?

**Comment by anihojnadel** [comment]
Please, send a snippet and the specific API version you are using. Reopen if still happening.
