### ISSUE TITLE
Cancel calendar event for organizer

### ISSUE THREAD

**Issue by jpanchal** [OfficeDev/Office-365-SDK-for-iOS#55]
Can we programmatically cancel an event if the user is an organizer? 

Accept and decline operations only apply on those events if user is not an organizer, otherwise it throws an error.

**Comment by anihojnadel** [comment]
Have you tried sending a MeetingMessage using the Cancelled meeting message type?

https://msdn.microsoft.com/office/office365/APi/complex-types-for-mail-contacts-calendar#EventResource

This is out of scope of our SDK, the REST Api decides which actions are supported and which are not.

Regards,
