### ISSUE TITLE
Change argument in ADALDependencyResolver

### ISSUE THREAD

**Issue by MIchaelMainer** [OfficeDev/Office-365-SDK-for-iOS#56]
Change ADALDependencyResolver initWithContext so that it takes ADAuthenticationContext instead of the qualification of the id, (id ADAuthenticationContext ). The ADAuthenticationContext class doesn't implement the ADAuthenticationContext protocol.

https://github.com/OfficeDev/Office-365-SDK-for-iOS/blob/master/sdk-objectivec/office365_odata_base/office365_odata_impl/ADALDependencyResolver.m

-(id)initWithContext : (id<ADAuthenticationContext>) context andResourceId : (NSString*)resourceId andClientId : (NSString*) clientId andRedirectUri : (NSURL*) redirectUri{
    
change to 

-(id)initWithContext : ADAuthenticationContext context andResourceId:(NSString*)resourceId andClientId : (NSString*) clientId andRedirectUri : (NSURL*) redirectUri{

**Comment by greathansen** [comment]
Updated in v0.9.0
