### ISSUE TITLE
Capitalization for Properties

### ISSUE THREAD

**Issue by joshgav** [OfficeDev/Office-365-SDK-for-iOS#57]
Consider making all `@property`'s lower-case per https://github.com/Microsoft/Vipr/issues/48.

**Comment by greathansen** [comment]
Hey, for this case, we just take the name from the metadata. When we generate the json data, we parse the object and then send it. The name of the json properties should match with the name deine in the metadata. To make all properties lower case, the endpoint should change the properties names.

Regards
Gus

**Comment by MIchaelMainer** [comment]
That'd make it easy for objective-c and other languages where properties are lowercased. Changing the case in the CSDL would push the problem out to .Net client libraries since properties are capitalized in .Net. Cost of convention versus ease of generation.

**Comment by greathansen** [comment]
updated code style in v0.9.0
