### ISSUE TITLE
Property attributes are implicit

### ISSUE THREAD

**Issue by MIchaelMainer** [OfficeDev/Office-365-SDK-for-iOS#58]
All of the property declarations use the default property attributes. None of them are explicitly declared. 

https://github.com/OfficeDev/Office-365-SDK-for-iOS/blob/master/sdk-objectivec/office365_exchange_sdk/Generated/Models/MSOutlookContact.h
https://github.com/OfficeDev/Office-365-SDK-for-iOS/blob/master/sdk-objectivec/office365_exchange_sdk/Generated/Models/MSOutlookEntity.h

For example, atomic is the default attribute, which means access to the property is thread-safe. Is this what we want on these properties? Probably not what is intended for these properties. 

Also, all properties are set as read-write as default. For example, identifiers are read-only.

**Comment by greathansen** [comment]
Fixed in v0.9.0
