### ISSUE TITLE
iPad2 simulator serializes enum values w/o quotes

### ISSUE THREAD

**Issue by MIchaelMainer** [OfficeDev/Office-365-SDK-for-iOS#60]
Strange behavior. I'm just checking that this is not caused by SDK (I doubt, but want to make sure). When creating an event (and other items) with a POST, all simulators besides iPad2 create the following successful payload (note enum values in quotes):
{
    "Subject": "New event created on 2015-24-03 at 10:04",
    "Body": {
        "@odata.type": "#Microsoft.OutlookServices.ItemBody",
        "ContentType": "0",
        "Content": "Congratulations, you created  this event from the Snippets app!"
    },
    "Importance": "0",
    "HasAttachments": "false",
    "Start": "2015-03-24T10:04:30Z",
    "End": "2015-03-24T11:04:30Z",
    "ShowAs": "0",
    "IsAllDay": "false",
    "IsCancelled": "false",
    "IsOrganizer": "false",
    "ResponseRequested": "false",
    "Type": "0",
    "Attendees": [
        {
            "Type": "0",
            "@odata.type": "#Microsoft.OutlookServices.Attendee",
            "EmailAddress": {
                "@odata.type": "#Microsoft.OutlookServices.EmailAddress",
                "Address": "admin@contoso.com"
            }
        }
    ],
    "@odata.type": "#Microsoft.OutlookServices.Event"
}
On an iPad simulator, the enum values are not in quotes and are rejected by the service:
{
    "Subject": "New event created on 2015-24-03 at 10:02",
    "Body": {
        "@odata.type": "#Microsoft.OutlookServices.ItemBody",
        "ContentType": 0,
        "Content": "Congratulations, you created  this event from the Snippets app!"
    },
    "Importance": 0,
    "HasAttachments": "false",
    "Start": "2015-03-24T10:02:30Z",
    "End": "2015-03-24T11:02:30Z",
    "ShowAs": 0,
    "IsAllDay": "false",
    "IsCancelled": "false",
    "IsOrganizer": "false",
    "ResponseRequested": "false",
    "Type": 0,
    "Attendees": [
        {
            "Type": 0,
            "@odata.type": "#Microsoft.OutlookServices.Attendee",
            "EmailAddress": {
                "@odata.type": "#Microsoft.OutlookServices.EmailAddress",
                "Address": "admin@contoso.com"
            }
        }
    ],
    "@odata.type": "#Microsoft.OutlookServices.Event"
}
I haven't tested on actual device. Per spec, these should be in quotes. Is there a different serializer for iPad2?

**Comment by anihojnadel** [comment]
This should now be fixed. Check the new version: https://github.com/OfficeDev/Outlook-SDK-iOS
