### ISSUE TITLE
case sensitivity

### ISSUE THREAD

**Issue by jerrchen** [OfficeDev/Office-365-SDK-for-iOS#67]
would it be possible to have the library build through a case sensitive file system?  For example, the sdk tries to include MSODataURL.h, but the real file name is MSODataUrl.h ...

**Comment by jerrchen** [comment]
same issue for some Podfiles including ADALiOS and ADALIOS ...  same problem occurs in other components as well.

**Comment by joshgav** [comment]
Thanks Jerry, we've fixed this in v0.14.0 which is making its way into the dev branches currently.
