### ISSUE TITLE
Simple-drive-app

### ISSUE THREAD

**Issue by ginesguirpa** [OfficeDev/Office-365-SDK-for-iOS#73]
Hi all,

I am trying to sign in Office365 running the app in my device. The sign in process finish with OK but I can read in the log this:

ERROR: Error raised: 11. Additional Information: Domain: ADAuthenticationErrorDomain ProtocolCode:(null) Details:Cannot add a new item in the keychain. Error code: -25243. Attributes: {
    acct = xxxxx
    svce = xxxxxx
}. ErrorCode: 11.

Then if I get my files info I can't because I have problem with the authorization.

My solution is comment that line:

"ADKeyChainHelper.h"

#if !(TARGET_IPHONE_SIMULATOR)
        [attributes setObject:_sharedGroup forKey:(__bridge id)kSecAttrAccessGroup];
#endif

is it correct??

**Comment by tranhieutt** [comment]
Hi @ginesguirpa:
Can you solve it?
I have similar trouble when I run app in my real device.

**Comment by anihojnadel** [comment]
It seems to be an ADAL for iOS issue. I've found the following in their github repo and in stackoverflow, could you please try it and let us know if worked?

https://github.com/AzureAD/azure-activedirectory-library-for-objc/issues/241

http://stackoverflow.com/questions/30876085/adalioscannot-add-a-new-item-in-the-keychain-o365-ios-connect-swift

**Comment by tranhieutt** [comment]
Thank you very much, I can do it.
========
Step 1:
Xcode > Target > Capabilites > Keychain Sharing -> Switch to ON 
Step 2:
add com.microsoft.adalcache into Keychain Group.
========
