### ISSUE TITLE
Simple-drive-app load Metadata

### ISSUE THREAD

**Issue by ginesguirpa** [OfficeDev/Office-365-SDK-for-iOS#74]
Hi All,

In the sample when I do sign up and then get files the server respond:

domain: @"Error in the Request" - code: 403

If I reload the view ( get files again ) the server respond OK

**Comment by anihojnadel** [comment]
I tried the sample and couldn't reproduce this behaviour. Is it still happening?
Notice that with the new version of the sdk you have tu update some headers to make it work (you have everything updated in DEV branch, we'll merge to master in next release)
