### ISSUE TITLE
login_hint for oauth2

### ISSUE THREAD

**Issue by jerrchen** [OfficeDev/Office-365-SDK-for-iOS#76]
Is there a way to sign in oauth2 and pass in the login_hint field for the default email address?  (better yet to directly jump to the customized oauth2 login screen for the tenant?)

**Comment by marcote** [comment]
Hi there,
This a more ADAL IOS related question. From my understanding, yes, you can pass the hint, please check this:

https://github.com/AzureAD/azure-activedirectory-library-for-objc/blob/e68a764a45dcacd99a5af349be3ea6a0181b7333/ADALiOS/ADALiOS/ADAuthenticationContext.m#L1357

Thanks
