### ISSUE TITLE
Can i use this SDK to get room lists and rooms?

### ISSUE THREAD

**Issue by dowi** [OfficeDev/Office-365-SDK-for-iOS#78]
as in here
https://msdn.microsoft.com/EN-US/library/office/dd899416(v=exchg.150).aspx

thanks!

**Comment by marcote** [comment]
Hi @dowi 
No, the mentioned operations are not part of the ODATA REST API we use. 
The link you mention is from another, non-ODATA API, and our SDK does not work with it.

Thanks,
Marcos

**Comment by dowi** [comment]
ok thanks!
