### ISSUE TITLE
MSOutlookServicesEvent with reminder set to "NONE"

### ISSUE THREAD

**Issue by siddheshcnaik** [OfficeDev/Office-365-SDK-for-iOS#80]
Hi,

Is there a way for creating MSOutlookServiceEvent with "Reminder" set to "None". Currently, "Reminder" is an integer value. When we create a calendar event with out setting Reminder, it creates an event with Reminder set to 0. 

Thanks,
Siddhesh

**Comment by anihojnadel** [comment]
Hi @siddheshcnaik,

The way to set a reminder changed in the current version of the SDK because the API REST changed and we had to regenerate the code.
It uses something called MSOutlookPatternedRecurrence.
You should update your SDK version to target the new one.
