### ISSUE TITLE
Can I use this SDK to download file from Office365/OneDrive

### ISSUE THREAD

**Issue by tranhieutt** [OfficeDev/Office-365-SDK-for-iOS#81]
Hi, 
I am using demo simple-drive-app in Office-365-SDK-for-iOS.
I can login successful and can display all files from  Office365/OneDrive/Documents in demo simple-drive-app.
So, I want to use this SDK to download files from Office365/OneDrive/Documents.
Please show me how to can i download files?
Thank you!

**Comment by tranhieutt** [comment]
Today, I can download files from Office365/OneDrive/Documents with code:

 [[[weakSelf.client.files getById:@"01JQ3FQBQAAUELI35YJBF2L5NCI3PR5DHU"] asFile] getContentWithCallback:^(NSData *content, MSOrcError *error) {

}];
But, I don't know how to download list items in sub-folder.
Can anyone help me?

**Comment by anihojnadel** [comment]
Hi @tranhieutt ,

To download children items from a folder you should use:

[[[[_weakSelf.client.files getById:itemId] asFolder] children] readWithCallback:^(id response, MSOrcError *error) {
            
 } ];

Let us know if you have any other question.
Regards!

**Comment by tranhieutt** [comment]
Thank @anihojnadel very much!
I can do it.
