### ISSUE TITLE
Edit file office in Office-365-SDK

### ISSUE THREAD

**Issue by tranhieutt** [OfficeDev/Office-365-SDK-for-iOS#84]
I have question.

With Office-365-SDK, currently, I can upload/download files from OneDrive to my App.
But now I want to edit file Office by using Office-SDK.
How/What should i use API to edit file office.
And after edit file successfully, how can i save file to my app?
I see in Dropbox app which can edit file office in Microsoft Office/Excel and save- backed to Dropbox.
Please show me the way to edit file office.
Thank you!

**Comment by tranhieutt** [comment]
HI @anihojnadel, I'm sorry, can you help me?
Thank!

**Comment by anihojnadel** [comment]
I'm not sure if I understood your scenario. What you want is to update the content of an existing file? If this is the case, there's a test that does exactly that operation, you can see the code here:

https://github.com/OfficeDev/Office-365-SDK-for-iOS/blob/master/test/sdk_tests/sdk_tests/FilesTestRunner.m#L234

If it is a different issue, please let us know.

**Comment by tranhieutt** [comment]
Thank your reply.
> What you want is to update the content of an existing file? If this is the case, there's a test that does exactly that operation, you can see the code here
- OK, I understood. No problem with file with extension of file is .txt.
But with file with extension is .doc, .docx or .xls, .xlsx, can i edit file?
Example, I have two app:
1. My app: I can get list file from Office365/OneDrive.
2. Word app:
https://itunes.apple.com/us/app/microsoft-word/id586447913?mt=8
or Excel:
https://itunes.apple.com/us/app/microsoft-excel/id586683407?mt=8

If I want to edit file Office [ extension of file  is .doc, docx]:
1. Firsly,  Can I use Office365 SDK to send my file to Word app/Excel app
2. Then, I edit this file in Word app.
3. Finally, can i save this file to my app?

Question here is:
Does Office 365 SDK support to  edit file in Word app and save-backed to my app?

**Comment by anihojnadel** [comment]
Our SDK is to consume the REST Api, it lets you download a file, update ir, etc.

In the scenario you describe, you can download the file using the SDK, update it using the other app, and then upload the modified file using the SDK again.
It should work, because you should send a stream of data no matter which type of file are you working with.

Regarding how to integrate the app with the editor, that's up to you, depends on the application you're building and the functionality of the editor.

**Comment by tranhieutt** [comment]
thank you, i understood.
