### ISSUE TITLE
Unable to fetch user calendar using iOS SDK

### ISSUE THREAD

**Issue by appcurry** [OfficeDev/Office-365-SDK-for-iOS#85]
We are using the iOS SDK to fetch user's calendar events which was working fine until today. Internally it calls the REST API with URL: https://outlook.office365.com/api/v1.0/Me/Events

However, it started failing today and the error happens during the conversion of the response data into JSON string. The response we get is:

{
 "@odata.context":"https://outlook.office365.com/api/v1.0/$metadata#Me/Events",
 "value":[{"error":{"code":"ErrorInternalServerError","message":"Object reference not set to an instance of an object."}}]
}

The corresponding request is:
HTTP Request <NSMutableURLRequest: 0x174203bb0> { URL: https://outlook.office365.com/api/v1.0/Me/Events/ }
URL: https://outlook.office365.com/api/v1.0/Me/Events/
Header fields: {
    Authorization = "Bearer eyJ0eXAiOiJKV1Q............RrizisXd-okQ";
    "Content-Type" = "application/json";
    "OData-MaxVersion" = "4.0";
    "OData-Version" = "4.0";
    "User-Agent" = "MSOutlookServicesClient/1.0 (lang=Objective-C; os=iPhone OS; os_version=8.4.1; arch=Other; version=6)";
    "X-ClientService-ClientTag" = "Rooms/1.0 (lang=Objective-C; os=iPhone OS; os_version=8.4.1; arch=Other; version=6)";
}

We are using 0.9.0 version of the SDK.
Any help will be much appreciated.

**Comment by appcurry** [comment]
It looks like this issue has impacted other developers as well: 
http://stackoverflow.com/questions/32585419/office-365-rest-api-me-events-no-longer-working

It just stopped working on 09/13. We updated to 0.11.0 SDK but still the same issue.

*Any feedback from O365 SDK developers in this forum ?*

**Comment by jerrchen** [comment]
Same problem here.  Started 9/11/2015 night PST time.

**Comment by anihojnadel** [comment]
Hi guys,

It seems to be some REST Api issue, we could reproduce the error and escalated the problem with the API people.
We'll let you know as soon as we have any information.

Thanks!

**Comment by anihojnadel** [comment]
The issue should now be solved. 

Additionally, we have released a new version of the SDK that uses the endpoint announced yesterday in Connect event. 
To use this endpoint, please download the new SDK and follow the instructions:
https://github.com/OfficeDev/Outlook-SDK-iOS
