### ISSUE TITLE
Get hostName in AuthenticationController [simple-drive-app]

### ISSUE THREAD

**Issue by tranhieutt** [OfficeDev/Office-365-SDK-for-iOS#86]
I have a question.
I see in [simple-drive-app]/base/BaseController.m
Line 12
======
+(void)getClient : (void (^) (MSSharePointClient *))callback{
    
    AuthenticationController *authenticationController = [AuthenticationController getInstance];
    NSString *hostName = @"https://msopentechtest01-my.sharepoint.com";
    
    [authenticationController initialize:hostName :true completionHandler:^(bool authenticated) {
        
        if (authenticated) {
            
            callback([[MSSharePointClient alloc] initWithUrl:[hostName stringByAppendingString:@"/_api/v1.0/me"] dependencyResolver:[authenticationController getDependencyResolver]]);
        }
        else {
            
            NSLog(@"Error in the authentication");
        }
    }];
}
=======

If I have had Microsoft Office 365 account, how can i get hostname string like @"https://msopentechtest01-my.sharepoint.com"? by request what URL?

If not, i must to "hard code" host name with each  MicroOffice 365 account. It's not  good for user.
Please show me the way get hostName by request what URL?

**Comment by ZuzooVn** [comment]
I have the same problem.

Anybody know the solution?

Thanks

**Comment by anihojnadel** [comment]
Hi, you can find that information using the Discovery SDK.

The GetServices/GetAllServices methods expose that information.

Resource for ADAL: https://api.office.com/discovery
Endpoint: https://api.office.com/discovery/v1.0/me

Regards,

**Comment by tranhieutt** [comment]
Thank for your help.

I printed my code is here

    NSString *clientId = @"YOUR_CLIENT_ID";
    NSURL *redirectUri = [NSURL URLWithString:@"YOUR_ redirectUri"];
    ADAuthenticationContext *authenticationContext = [ADAuthenticationContext authenticationContextWithAuthority:@"https://login.microsoftonline.com/common/" error:nil];
    [authenticationContext acquireTokenWithResource:@"https://api.office.com/discovery/" clientId:clientId redirectUri:redirectUri completionBlock:^(ADAuthenticationResult *result) {
        if (result.status == AD_SUCCEEDED) {
            // Authentication succeeded
            NSURL *URL = [NSURL URLWithString:@"https://api.office.com/discovery/v1.0/me/services"];
            //
            NSMutableURLRequest *request = [NSMutableURLRequest requestWithURL:URL];
            NSURLSessionConfiguration *config = [NSURLSessionConfiguration defaultSessionConfiguration];
            NSURLSession *session = [NSURLSession sessionWithConfiguration:config];
            [request setValue:[NSString stringWithFormat:@"Bearer %@", result.accessToken] forHTTPHeaderField:@"Authorization"];
            [request setHTTPMethod:@"GET"];
            NSURLSessionDataTask *dataTask = [session dataTaskWithRequest:request completionHandler:^(NSData *data, NSURLResponse *response, NSError *error) {
                NSDictionary *dataJSON = [NSJSONSerialization JSONObjectWithData:data options:0 error:&error];
                NSLog(@"%@", dataJSON);
                if (dataJSON) {
                    NSArray *arrayOfValue = [dataJSON objectForKey:@"value"];
                    if (arrayOfValue.count) {
                        NSDictionary *serviceDic = [arrayOfValue firstObject];
                        NSString *hostName = [serviceDic objectForKey:@"serviceResourceId"];
                        AuthenticationController *authenticationController = [AuthenticationController getInstance];
                        [authenticationController initialize:hostName :true completionHandler:^(bool authenticated) {
                            if (authenticated) {
                            
                                callback([[MSSharePointClient alloc] initWithUrl:[hostName stringByAppendingString:@"/_api/v1.0/me"] dependencyResolver:[authenticationController getDependencyResolver]]);
                            }
                            else {
                                NSLog(@"Error in the authentication");
                            }
                        }];
                    }
                }
            }];
            [dataTask resume];
        }
        else if (result.status == AD_USER_CANCELLED) {
            // Authentication cancelled by the user
        }
        else {
            // Authentication failed
        }
    }];

Please ref:
http://blog.beecomedigital.com/2015/02/21/use-adal-for-ios-osx-with-o365-discovery-rest-api/

**Comment by anihojnadel** [comment]
FYI, All the code you're using after getting the token is available in the Discovery SDK. Basically, it does the same but in a simpler way.

You create the DiscoveryClient and then call the method to get the services.
