### ISSUE TITLE
Creating .ics file from MSOutlookEvent

### ISSUE THREAD

**Issue by siddheshcnaik** [OfficeDev/Office-365-SDK-for-iOS#87]
Hi,

Is there a way for creating an ICS file from MSOutlookEvent.

Thanks

**Comment by anihojnadel** [comment]
This is something API specific. We reviewed the metadata of the API from which we generate our SDKs and doesn't seems to have something to generate ICS files. 

We already asked the API owners to confirm this. Once we have the confirmation from them we'll let you know.

**Comment by anihojnadel** [comment]
We asked the API owners and they confirmed us that you can't create an .ics using the API by now.

Thanks!
