### ISSUE TITLE
Preview file in Office 365 SDK for IOS ???

### ISSUE THREAD

**Issue by ishrek** [OfficeDev/Office-365-SDK-for-iOS#89]
How do preview file in SDk???

please help

**Comment by tranhieutt** [comment]
Yes, you can use this code:
====
[[[self.client.files getById:[YOUR_FILE_ID]] asFile] getContentWithCallback:^(NSData *content, MSOrcError *error) {
    dispatch_async(dispatch_get_main_queue(),
                   ^{
                       // you can convert "content" to image here and Preview
                   });
}];
====

**Comment by anihojnadel** [comment]
You can't preview the file without downloading it all. You should first download the hole file and then show it in you application.

Thanks!
