### ISSUE TITLE
Session timeouts for Office 365 SDK for iOS

### ISSUE THREAD

**Issue by tranhieutt** [OfficeDev/Office-365-SDK-for-iOS#90]
Sorry, I have question.
How long the session time-out periods when I use:
1. SharePoint Online service [to get list files and folders]
2. Azure Active Directory service

Here is it correct answer?
https://support.office.com/en-us/article/Session-timeouts-for-Office-365-37a5c116-5b07-4f70-8333-5b86fd2c3c40

Thank you!

**Comment by marcote** [comment]
Hi @tranhieutt . What resource / service are you asking for? We don't the answer, but we can try to route it to the API Owners.

Thanks,
Marcos

**Comment by tranhieutt** [comment]
Hi @marcote, thank for your reply.
I mean, when I sign in Office 365 service by using Office 365 SDK, how long i must to re-sign in again? 24 hour? or 2 days?

**Comment by anihojnadel** [comment]
Hi @tranhieutt,

The token expiration is something we can't handle, to perform the login we use an external library. You should ask ADAL team for more information.

https://github.com/AzureAD/azure-activedirectory-library-for-objc

Thanks!
