### ISSUE TITLE
Create folder in Office 365 ???

### ISSUE THREAD

**Issue by ishrek** [OfficeDev/Office-365-SDK-for-iOS#91]
How to create folder in office 365. Please help me

**Comment by tranhieutt** [comment]
You can use:
    MSSharePointItem *item = [[MSSharePointItem alloc] init];
    item.name = @"ABCDEF";
    item.type = @"Folder";
    
    [self.client.files  add:item callback:^(MSSharePointItem *item, MSOrcError *error) {
        NSLog(@"%@",item);
    }];

If you want to create folder in sub-folder, you can use:
    [[[[self.client.files getById:self.currentDocumentId] asFolder] children] add:item callback:^(MSSharePointItem *item, MSOrcError *error) {
        NSLog(@"%@",item);
    }];

**Comment by anihojnadel** [comment]
What @tranhieutt  is OK if you're using Files. You can also create folders for Outlook and it's different.

Which API are you using? (SharePoint, Outlook, etc)

Thanks!

**Comment by tranhieutt** [comment]
I use API in:
http://cocoadocs.org/docsets/Office365/0.11.0/Classes/MSSharePointItemCollectionFetcher.html#//api/name/add:callback:

**Comment by tranhieutt** [comment]
@ishrek , this issue is solved.
Could you close this issue?
