### ISSUE TITLE
MSOrcError 

### ISSUE THREAD

**Issue by siddheshcnaik** [OfficeDev/Office-365-SDK-for-iOS#93]
Is there a list of all possible MSOrcError codes, that could be returned while creating, deleting or updating an MSOutlookEvent?

**Comment by anihojnadel** [comment]
No, we don't have an error code list. This SDK is a wrapper to perform the REST calls against the REST API, the errors we could get are those related to the API (see API documentation https://msdn.microsoft.com/en-us/office/office365/api/api-catalog#Outlookcalendar).

Thanks!
