### ISSUE TITLE
Search file/folder in Office-365-SDK-for-iOS

### ISSUE THREAD

**Issue by tranhieutt** [OfficeDev/Office-365-SDK-for-iOS#94]
Hi all!
I want to implement to search file/folder in SDK.
Should I use what/how API?
Thank you!

**Comment by tranhieutt** [comment]
in SDK, i found this code:
[[[self.client.files search:@”123456″] addCustomParametersWithName:@”Querytext” value:@”sharepoint”] readWithCallback:^(id response, MSOrcError *error) {
NSLog(@””);
}];

But I can’t know how to use correct string in search and correct Parameters and value…

**Comment by anihojnadel** [comment]
Hi @tranhieutt !
We are in the middle of a big realease for next week, we'll start answering issues after Connect! Please be patient :) 

Thanks in advance!

**Comment by anihojnadel** [comment]
We have different APIs, each one for different services form Office365. Which service are you using? Sharepoint? OneDrive for Business?  is really important to know that in order to be able to help you.

The code you're using is not valid in any SDK. Please, send us more information and we'll try to answer ASAP.

**Comment by tranhieutt** [comment]
I use search API in:
http://cocoadocs.org/docsets/Office365/0.11.0/Classes/MSSharePointItemCollectionFetcher.html#//api/name/search:

**Comment by anihojnadel** [comment]
You should better use filter method. For instance: filter "PropertyName eq 'yourvalue'". That will retrieve all entities with "PropertyName" with value "yourvalue".

Let us know if this helped.

**Comment by anihojnadel** [comment]
Check filter operations here:
http://docs.oasis-open.org/odata/odata/v4.0/errata02/os/complete/part1-protocol/odata-v4.0-errata02-os-part1-protocol-complete.html#_Toc406398301

**Comment by tranhieutt** [comment]
thank you, I'll close this issue.
