### ISSUE TITLE
Upload file which is exist in List items ( or replace item

### ISSUE THREAD

**Issue by tranhieutt** [OfficeDev/Office-365-SDK-for-iOS#95]
Sorry, I have a question.
[Precondition]
Login Office 365 via SDK.
[Steps to reproduce]
1.Upload file with name: ABC.jpg to folder A
My source is:

            [[[[self.client.files getById:self.currentDocumentId] asFolder] children] add:item callback:^(MSSharePointItem *item, MSOrcError *error) {
                __block NSString* _id = item.id;
                if (!error) {
                    [[[[[[self.client.files getById:self.documentId] asFolder] children] getById:_id] asFile] putContent:body callback:^(NSInteger statusCode, MSOrcError *uploadError) {
                        dispatch_async(dispatch_get_main_queue(),
                                       ^{
                                           if (!uploadError) {
                                           } else {
                                               //                                           Error
                                           }
                                       });
                    }];
                }else {
                    dispatch_async(dispatch_get_main_queue(), ^{
                        //Error Duplicate
                    });
                }
            }];

2.Upload successful
3.Upload file ABC.jpg to folder A again.

So, SDK return error:

Error Domain=Error in the Request Code=409 "(null)" UserInfo={error={
    code = NameAlreadyExists;
    message = "A resource with the same name already exists";
}}

Currently, I want to replace file which exist in List items.
Question is:
What API should I use to replace file which exist in List items.
Thank you!

**Comment by anihojnadel** [comment]
Which API are you using? Sharepoint Lists or Files?

**Comment by anihojnadel** [comment]
In case you're using Files API, are you doing the add twice? If that's the case, you shouldn't.

If you want to update some of the file information (for instance, name). You should get the file and do an update. If you just want to update the content, you should call the PutContent again.

Thanks!

**Comment by ishrek** [comment]
@anihojnadel i used code 
[[[[self.client.files getById:self.currentDocumentId] asFolder] children] add:item callback:^(MSSharePointItem *item, MSOrcError *error) {
                __block NSString* _id = item.id;

when return error code = 409 , i can't get item.id => not update file existed

Please help me???

**Comment by anihojnadel** [comment]
Could you send us the error message you're receiving? If there's an error, the item will be null. We need yo know the error first.

**Comment by tranhieutt** [comment]
We just used this source code:
```
[[[[[[[self.client.files getById:self.documentId] asFolder] children] getById:_id] asFile] addCustomHeaderWithName:@"If-Match" value:@"*"] putContent:body callback:^(NSInteger statusCode, MSOrcError *uploadError) {
                      
                        dispatch_async(dispatch_get_main_queue(),
                                       ^{
                                           //
                                           
                                       });
                    }];
```
We close this issue.
Thank you!
