### ISSUE TITLE
Delete multi-items in List items

### ISSUE THREAD

**Issue by tranhieutt** [OfficeDev/Office-365-SDK-for-iOS#96]
Sorry, I have a question about delete function in SDK.
If i want delete 1 item, folder or file, i can use source code:

    [[[self.client.files getById:data.fileId] addCustomHeaderWithName:@"If-Match" value:@"*"] deleteWithCallback:^(int status, MSOrcError *error) {
            NSLog(@"OK");
    }];

So, if I want to delete multi-item, question is:
- What API should I use to delete multi-items in list items?

If SDK doesn't support delete multi-item, I must use loop for.
Ex:
for (NSString *fileID in arrrayOfFileID) {
   
    [[[self.client.files getById: fileID] addCustomHeaderWithName:@"If-Match" value:@"*"] deleteWithCallback:^(int status, MSOrcError *error) {
            NSLog(@"OK");
    }];
}

I think solution above is not good for iOS app.

Please show me API can delete multi-items.
Thank you.

**Comment by anihojnadel** [comment]
Hi @tranhieutt , the API doesn't support deleting multi-items. You should use the second approach.

Thanks!
