### ISSUE TITLE
MSOrcError : errror code 412

### ISSUE THREAD

**Issue by ishrek** [OfficeDev/Office-365-SDK-for-iOS#98]
i update file existed in Office 365
i use this code
`
[[[weakSelf.client.files getById:__id] asFile] putContent:body callback:^(NSInteger result, MSOrcError *error) {
        dispatch_async(dispatch_get_main_queue(),
                       ^{
                           if (!error) {
                               if (tempUploadFileList.count > 0) {
                                   // still have file to upload
                                   [weakSelf uploadMutilFile];
                               }else {
                                   if (weakSelf.alert.visible) {
                                       [weakSelf.alert dismissWithClickedButtonIndex:NO animated:YES];
                                   }
                                   [weakSelf dismissViewControllerAnimated:YES completion:^{
                                       if (weakSelf.isUploadFromLocal) {
                                           if (weakSelf.uploadToOffice365FileSuccessBlock) {
                                               weakSelf.uploadToOffice365FileSuccessBlock(weakSelf.currentDocumentId, weakSelf.navigationItem.title,DOCUMENT_VIEW_LOCATION_OFFICE_365,weakSelf.client);
                                           }
                                       }else {
                                           if (weakSelf.uploadFileSuccessBlock) {
                                               weakSelf.uploadFileSuccessBlock(weakSelf.currentDocumentId, weakSelf.navigationItem.title,DOCUMENT_VIEW_LOCATION_OFFICE_365,weakSelf.othersDocsPermission);
                                               isForceUpload = NO;
                                               overwriteAll = NO;
                                           }
                                       }
                                   }];
                                  
                               }
                           } else {
                               NSLog(@"%ld",(long)[error code]);
                           }
                       });
    }];
`
But throw error code : 412 
`2016-02-22 18:14:09.544 C-Portal-O[22410:150674] 412`
@"message" : @"The request ETag value '' does not match the object's ETag value '\"{DBBE5A7B-1070-4DE2-9617-AEE3C0B111F2},1\"'."

Please help me???. thanks

**Comment by tranhieutt** [comment]
All message error is:


> Error Domain=Error in the Request Code=412 "(null)" UserInfo={error={
>     code = "-1, Microsoft.SharePoint.Client.ClientServiceException";
>     message = "The request ETag value '' does not match the object's ETag value '\"{DDD84480-D23B-4EBA-99A8-5985FB7084E0},1\"'.";
> }}

@anihojnadel , could you please help us?

**Comment by anihojnadel** [comment]
Try adding the If-Match header like in this test:

https://github.com/OfficeDev/Office-365-SDK-for-iOS/blob/master/test/sdk_tests/sdk_tests/FilesTestRunner.m#L426

**Comment by ishrek** [comment]
thank you @anihojnadel
